name: Exploring Variables and Secrets
on: push

jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: docker build -t $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest
      
    - name: Docker login
      run: docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}
      
    - name: Docker Publish
      run: docker push $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy: 
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest
